INSERT INTO USERS  ( name, email, username, password)  VALUES( 'Administrador Sistemas', 'admcapes@gmail.com', 'admin','12345678900');

INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES( 'Academic Search Premier - ASP (EBSCO)', 'Base de dados multidisciplinar que conta com mais de 2.500 periódicos em texto completo em todas as áreas do conhecimento. Também estão disponíveis referências e resumos de diferentes tipos de documentos, publicados desde 1911. Os documentos podem ser descarregados em formatos PDF ou HTML.', 'EBSCO', 'https://login.ebsco.com/', true, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('ACM Computing Reviews', 'ACM Computing Reviews (ISSN impresso: 0010-4884; ISSN Online 1530-6585) é uma base de dados de referências que contém resumos e revisões da literatura em ciência da computação, é uma publicação mensal da Association for Computing Machinery (ACM) produzida em colaboração com a Thinkcloud. Nela é publicada revisões da literatura de ciência da computação. O banco de dados da ACM Computing Reviews é grande e abrangente, composto de revisões que cobrem a literatura das áreas relacionadas à computação', 'Association for Computing Machinery (ACM)', 'https://www.computingreviews.com/index_dynamic.cfm?CFID=98929875&CFTOKEN=83829451', true, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('Proposta e Avaliação de uma Metodologia de Aprendizagem Baseada em Projetos em Disciplinas de Engenharia de Software através de uma Sequência Didática', ' Ciência da Computação, mais especificamente na área de Engenharia de Software. Enquanto por um lado, as aulas tradicionais possuem ... Aprendizagem Baseada em Projetos em uma disciplina de Engenharia de Software, de forma que os estudantes, ainda durante sua ... Esta experiência, avaliada em uma turma regular de Engenharia de Software de um Bacharelado em Ciência da Computação, foi ...', 'Revista Brasileira de Informática na Educação', 'https://journals-sol.sbc.org.br/index.php/rbie/article/view/2817', false, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('Uso de Métodos Ágeis e Aprendizagem Baseada em Problema no Ensino de Engenharia de Software: Um Relato de Experiência', '... acompanhar essa transformação o processo de ensino em Engenharia de Software também tem evoluído, para criar novas habilidades aos ... relatar a experiência de alunos no aprendizado de engenharia de software, utilizando como proposta pedagógica a aprendizagem baseada em problema e o uso de scrum para construção de um projeto real, aplicado para dispositivos móveis.', 'Anais do ... Simpósio Brasileiro de Informática na Educação/Anais do Simpósio Brasileiro de Informática na Educação', 'https://tophotels.com/tecnologia-da-informacao-no-sistema-educacional-do-brasil.pt-br', true, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('Panorama do Ensino de Engenharia de Software em Cursos de Graduação Focado em Teste de Software: Uma Proposta de Aprendizagem Baseada em Jogos', 'Este trabalho apresenta um panorama do ensino de engenharia de software em cursos de graduação na área de computação ... ao ensino-aprendizagem de estratégias de teste de software.', 'Associação Sul-Rio-Grandense de Pesquisadores em História da Educação (ASPHE) | RENOTE', 'https://seer.ufrgs.br/renote/article/view/25115', false, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('Definição de requisitos de software baseada numa arquitetura de modelagem de negócios', '... desenvolvimento baseado nos reais objetivos do negócio. A engenharia de software carece de métodos que tornem mais ordenadas e ...', 'Associação Brasileira de Engenharia de Produção | Production', 'https://www.scielo.br/j/prod/a/4fyvdWfsVyDQRfhqTCRJ8vL/?lang=pt', false, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('Em busca de uma proposta metodológica para o desenvolvimento de software educativo colaborativo', '... as diferentes metodologias de desenvolvimento propostas pelaárea de engenharia de software. Esta metodologia está sendo validada na construção doambiente ...', 'Associação Sul-Rio-Grandense de Pesquisadores em História da Educação (ASPHE) | RENOTE', 'https://seer.ufrgs.br/renote/article/view/13998', true, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('CBPF INDEX', 'resumos de livros, descritivos de processos, protótipos e softwares etc desenvolvidos pela comunidade do CBPF.', 'Centro Brasileiro de Pesquisas Físicas (CBPF)', 'https://cbpfindex.cbpf.br/', false, false);
INSERT INTO CONTENT  ( name, resumen, font, link, futureJob, isFavorite)  VALUES('Directory of Open Access Repositories : OpenDOAR', 'baseado na categorização por características, como a localização, software ou tipo de material mantido.', 'Lund University. Libraries + University of Nottingham. Information Services', 'https://v2.sherpa.ac.uk/opendoar/', false, false)








